name: PR - Verify linked issue

on:
  pull_request:
    types: [edited, synchronize, opened, reopened]
  workflow_dispatch:

jobs:
  PR_verifyLinkedIssue:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.7

      - name: Regex on PR Body
        id: regex_pr_body
        uses: actions-ecosystem/action-regex-match@v2.0.2
        with:
          text: ${{ github.event.pull_request.body }}
          regex: 'https:\/\/github.com\/[a-zA-Z0-9_-]+\/[a-zA-Z0-9_-]+\/issues\/[0-9]+|#[0-9]+|[a-zA-Z0-9_-]+\/[a-zA-Z0-9_-]+#[0-9]+'

      - name: Check for Linked Issue
        id: check_linked_issue
        run: |
          linked_issue=${{ steps.regex_pr_body.outputs.match }}
          echo "Linked issue: $linked_issue"
          if [ -z "$linked_issue" ]; then
            echo "linked_issues=false" >> $GITHUB_ENV
          else
            echo "linked_issues=true" >> $GITHUB_ENV
          fi

      - name: Echo message for No Linked Issue
        run: echo "No linked issue found."
        if: ${{ env.linked_issues == 'false' }}

      - name: Comment for No Linked Issue
        uses: actions/github-script@v7
        if: ${{ env.linked_issues == 'false' }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issueNumber = context.issue.number;
            github.rest.issues.createComment({
              issue_number: issueNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Your PR description does not contain a linked issue. Please tag the corresponding issue using [keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) in your PR description. The flow will restart automatically after the edit. For more information, refer to the GitHub principles and conventions defined in [Git & GitHub & GitFlow | Notion](https://www.notion.so/roclub/Git-GitHub-GitFlow-85cbb825be004d4d8b8ff6c0fa12204b%29)`
            })

      - name: Fail for No Linked Issue
        run: exit 1
        if: ${{ env.linked_issues == 'false' }}
        
      - name: Step for Linked Issue(s)
        run: echo "Linked issue(s) found."
        if: ${{ env.linked_issues == 'true' }}
